### ISSUE TITLE
Doing two times a complete cycle of channel creation, the second call to CreateSmartChannel requires 5 minutes to complete.

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/DataDistributionManager#15]
**Describe the bug**
A second call to CreateSmartChannel, after StopChannel and SmartDataDistribution.Stop , using the same configuration to start SmartDataDistribution and SmartDataDistributionChannel, requires 5 minutes to complete.

**To Reproduce**
Do this initialization:
```
SmartDataDistribution dataDistribution = new SmartDataDistribution();
SmartDataDistributionChannel Channel;
OPERATION_RESULT Res = new OPERATION_RESULT();
```
Do this  sequence in code
```
[...]
//Configuration is a valid kafka configuration
Res = dataDistribution.Initialize(Configuration);
Res = dataDistribution.Start(uint.MaxValue);
Channel = dataDistribution.CreateSmartChannel<SmartDataDistributionChannel>(ChannelName, Configuration);
// The following line require 1-2 seconds to be executed
Res = Channel.StartChannel(uint.MaxValue);
// Here you are connected and the communication is active

Res = Channel.StopChannel(10000);
Res = dataDistribution.Stop(10000);

// Here you are ready to do a new run with the same configuration
Res = dataDistribution.Start(uint.MaxValue);
Channel = dataDistribution.CreateSmartChannel<SmartDataDistributionChannel>(ChannelName, Configuration);
//The following line requires 5 minutes to be executed
Res = Channel.StartChannel(uint.MaxValue);
```

**Expected behavior**
The first and the second call to CreateSmartChannel shall require the same time.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win 10 pro
 - Version 10.0.18362 

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
@marcocappolimases it is not clear which tranport layer you are using. From a comment seems to be Kafka, but I'm not sure. Do you confirm it is Kafka?
