### ISSUE TITLE
Under heavy stress condition the published payload is not correct

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/DataDistributionManager#17]
**Describe the bug**
Using the `WriteOnChannel` API sometimes the published value reports strange values

**To Reproduce**
The wrong behavior is not reproducible with a fixed sequence.
Create a loop to write continuously using `WriteOnChannel` then wait the error to appears.

**Expected behavior**
The value published shall be always the same written with `WriteOnChannel`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
OS: Win 10 pro
Version 10.0.18362

**Additional context**
Tested in C#, but should be the same in Java and C++

**Comment by mariomastrodicasa** [comment]
@marcocappolimases seems there is a problem between managed code and native code. Kafka transmits messages using an internal queue. The flags to use in the produce API can be setted externally with the `datadistributionmanager.kafka.producer.msgflags` parameter. The flags are the one reported in the librdkafka [header file](https://github.com/edenhill/librdkafka/blob/v1.6.0/src-cpp/rdkafkacpp.h#L2985). The defuat value currently is 0 and this means the library expect the payload pointer be invariant until the completion of the transmission.
Adding managed high-layer the pointer is under the control of the garbage collector, so I think it is important to change the dafault value to be `RK_MSG_COPY`: this is the same behavior used in the OpenDDS implementation.
