### ISSUE TITLE
Wrong parameter passed for AutoOffsetReset in KafkaChannelConfiguration

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/DataDistributionManager#19]
**Describe the bug**
Configuring a `KafkaChannelConfiguration` to `AutoOffsetResetType.beginning` beginning results in a wrong parameter passed during the subsystem initialization.

**To Reproduce**
1. Configure a C# project to use _DataDistributionManager_
2. Use the following configuration:
```
  KafkaConfiguration kConfiguration = new KafkaConfiguration()
  {
  
  };
  KafkaChannelConfiguration kChannelConfiguration = new KafkaChannelConfiguration(kConfiguration)
  {
      AutoOffsetReset = AutoOffsetResetType.beginning,
      ClientId = "MyID",
      GroupId = "MyGroup",
      BootstrapBrokers = "KAFKA_SERVER_IP:PORT",
  };
```
3. Define a delegate that write data to a log file or to console, and connect it to the _DataDistributionManager_ Instance _LoggingEvent_
`dataDistribution.LoggingEvent +=MY_LOG_WRITER_METHOD;`
4. Initialize the _DataDistributionManager_ Instance
`dataDistribution.Initialize(kChannelConfiguration );`
5. Read the log
6. Find the following messages in log: 
**datadistributionmanager.kafka.topicconf.compression.codec - Value : beginning** 
**set configuration: Invalid value "beginning" for configuration property "compression.codec"**

**Expected behavior**
the value `"beginning"` shall be configured for the `"datadistributionmanager.kafka.topicconf.auto.offset.reset"` parameter .

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Found in C# project, should be the same with other languages.

**Comment by mariomastrodicasa** [comment]
@marcocappolimases, waiting for a fix on this issue, exists a workaround for this issue which uses the special property setter. A possible code snippet can be the following:

```c#
  KafkaChannelConfiguration kChannelConfiguration = new KafkaChannelConfiguration(kConfiguration)
  {
      // AutoOffsetReset = AutoOffsetResetType.beginning,
      ClientId = "MyID",
      GroupId = "MyGroup",
      BootstrapBrokers = "KAFKA_SERVER_IP:PORT",
  };
  kChannelConfiguration[KafkaConfigurationType.TOPIC_CONF, "datadistributionmanager.kafka.topicconf.auto.offset.reset"] = "beginning";
```

**Comment by mariomastrodicasa** [comment]
Analyzing masesgroup/DDMChat#4 I discovered that the default value for offset is set to `-1`, which means in librdkafka `End`. Set the value of `auto.offset.reset` will impact consumers only if the offset value is invalid (see [CONFIGURATION.md](https://github.com/edenhill/librdkafka/blob/v1.6.1/CONFIGURATION.md) but `-1` is a valid value. It is important to add another property which will set the initial offset value of the channel.
