### ISSUE TITLE
Add a method to retrieve the actual Channel offset

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/DataDistributionManager#21]
** Is your feature request related to an issue? Please describe. **
It is not possible to know the actual offset of the _Channel_, this makes a correct use of the `Seek` method impossible.

** Describe the solution you want **
The `ChannelConfiguration` class has a method to retrieve the offset, but the security layer avoids its direct use, making this method public could be a possible solution.

** Describe the alternatives you have considered **
No alternative was considered.

** Additional context **
N / A

**Comment by mariomastrodicasa** [comment]
@marcocappolimases you are right about the usage of `Seek` in many conditions. The method `GetActualOffset`, within `ChannelConfiguration`, currently is for internal use. My idea is to report the latest offset using the event raised when a message is available. Then the value will be exposed from higher `Smart*` classes in C++, C# and Java.

**Comment by marcocappolimases** [comment]
> @marcocappolimases my idea is to report the latest offset using the event raised when a message is available. Then the value will be exposed from higher `Smart*` classes in C++, C# and Java.

@mariomastrodicasa This will be ok most of time but, in some condition, could be useful to seek in _Channel_ past elements before receive a first message. 
A possible solution can be the implementation of a `Seek` method that accepts negative values.

**Comment by mariomastrodicasa** [comment]
> > @marcocappolimases my idea is to report the latest offset using the event raised when a message is available. Then the value will be exposed from higher `Smart*` classes in C++, C# and Java.
> 
> @mariomastrodicasa This will be ok most of time but, in some condition, could be useful to seek in _Channel_ past elements before receive a first message.
> A possible solution can be the implementation of a `Seek` method that accepts negative values.

@marcocappolimases about the `Seek` I reference the related issue #22

**Comment by mariomastrodicasa** [comment]
@marcocappolimases I discovered that another interesting value is the timestamp of the last received message: it is related to the issue #22. There are other possible value that can be reported during the implementation of this issue?

**Comment by marcocappolimases** [comment]
@mariomastrodicasa seems to me that, at the moment, timestamp and offset are the only two values that have the same meaning in **Kafka** and **OpenDDS**. 
Other values could be passed in the future with a specific dictionary for each transport layer.
